name: "Bug Report"
description: "回報錯誤或異常狀況"
title: "[Bug] "
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: 錯誤說明
      description: "請描述錯誤內容及發生位置"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 重現方式
      description: "請描述可以重現錯誤的步驟"
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: 預期行為
      description: "預期應該出現的結果"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 補充資訊
      description: "可提供截圖等資料"
    validations:
      required: false
