name: "Feature Request"
description: "提出新功能需求"
title: "[Feature] "
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: 功能說明
      description: "請簡述該功能的目的與內容"
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 預計實現方式
      description: "描述可能的程式或架構實現方式"
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 相關資料
      description: "可附上文件、設計稿等"
    validations:
      required: false
